### PR TITLE
#6 Snackbar support

### PR DESCRIPTION
**Pull request by bezmian**
* Added method for showing snackbar
 * Updated README.md
 * Updated samples

### CODE REVIEW

**Comment by shaunidiot** [comment]
Please merge this. Pretty sure it's useful in showing useful messages to users while interacting with the activity.

**Comment by bezmian** [comment]
@shaunidiot Please be patient ;) We will release 0.0.4 version as soon as possible.

**Comment by radzio** [comment]
LGTM!

**Comment by shaunidiot** [comment]
@bezmian Just realized you're one of the contributors to this library.  Hope to see all your pull requests in the new version soon! Great job!

**Pull request merged**
